// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCz4LCAeUx2sBqjSH6AcnM3c4XeRn7mtQ',
    appId: '1:134003520128:web:9300f04d049c1ee599ec65',
    messagingSenderId: '134003520128',
    projectId: 'app-sekolah-dev',
    authDomain: 'app-sekolah-dev.firebaseapp.com',
    storageBucket: 'app-sekolah-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysvNRsi_oxAYroNuAPVnd5r_tFnJhMuk',
    appId: '1:134003520128:android:551c6962bd2343c299ec65',
    messagingSenderId: '134003520128',
    projectId: 'app-sekolah-dev',
    storageBucket: 'app-sekolah-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Z1wmqd0d3od6NVkNhhc_9gICOlBKih0',
    appId: '1:134003520128:ios:8ac82bef2564e02299ec65',
    messagingSenderId: '134003520128',
    projectId: 'app-sekolah-dev',
    storageBucket: 'app-sekolah-dev.firebasestorage.app',
    iosBundleId: 'com.example.appSekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Z1wmqd0d3od6NVkNhhc_9gICOlBKih0',
    appId: '1:134003520128:ios:8ac82bef2564e02299ec65',
    messagingSenderId: '134003520128',
    projectId: 'app-sekolah-dev',
    storageBucket: 'app-sekolah-dev.firebasestorage.app',
    iosBundleId: 'com.example.appSekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCz4LCAeUx2sBqjSH6AcnM3c4XeRn7mtQ',
    appId: '1:134003520128:web:72a90c853d27054c99ec65',
    messagingSenderId: '134003520128',
    projectId: 'app-sekolah-dev',
    authDomain: 'app-sekolah-dev.firebaseapp.com',
    storageBucket: 'app-sekolah-dev.firebasestorage.app',
  );
}
